name: Build All

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore SIGame dependencies
      run: dotnet publish --no-restore SIGame.sln -c Release -p:PublishSingleFile=true -r win-x64 --self-contained true -p:EnableCompressionInSingleFile=true /property:Version=7.0.9
    - name: Build SIGame
      run: dotnet build SIGame.sln
    - name: Deploy SIGame
      shell: bash
      run: |
        a=`find . | grep exe`
        echo $a
        
